### ISSUE TITLE
Error with inspiredminds/contao-wowjs and delirius/contao-structure-element extension

### ISSUE THREAD

**Issue by sdahlmann** [inspiredminds/contao-wowjs#6]
If I use the Contao extension "delirius/contao-structure-elements" and the extension "inspiredminds/contao-wowjs" is installed at the same time, I get the following error message when creating the Start-Structure Element as a DIV element: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'wowjsOffset' at row 1". Question: Is there an incompatibility with the structure element and can you fix it when you have a chance?

**Comment by fritzmg** [comment]
Please use the debug mode and post the full stack trace.

**Comment by sdahlmann** [comment]
An error message appears when creating the structure element, see PDF-File.
[An exception occurred while executing a query SQLSTATE[HY000] General error 1366 Incorrect integer value '' for column 'wowjsOffset' at row 1 (500 Internal Server Error).pdf](https://github.com/inspiredminds/contao-wowjs/files/11900380/An.exception.occurred.while.executing.a.query.SQLSTATE.HY000.General.error.1366.Incorrect.integer.value.for.column.wowjsOffset.at.row.1.500.Internal.Server.Error.pdf)

**Comment by fritzmg** [comment]
The problem lies within the `delirius/contao-structure-elements` extension in this line: https://github.com/delirius/contao-structure-elements/blob/e0706d7b0c3adf8714b4f739c3d8f04b60e93a72/src/BackendHelper/Helper.php#L152

The extension erroneously converts all values fetched from the database to a string and wraps them with quotes when inserting them back into the database. This means that `NULL` values will also get transformed to an empty string - which is then not allowed by the database for fields that are integers.

This needs to be fixed in the `delirius/contao-structure-elements` extension.
